[package]
name = "yew-app"
version = "0.1.0"
authors = ["vega"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
js-sys = "0.3.49"

[dependencies.web-sys]
version = "0.3"
features = [
  "DataTransfer",
]
